version: '3.9'

volumes:
  db:

services:
  app:
    image: wahyudotdev/my-notes:latest
    environment:
      PORT: "80"
      API_SECRET: "rahasia"
      BASE_URL: "http://3.0.19.212"
    restart: always
    ports:
      - "80:80"
    volumes:
      - db:/app